[workspace]
resolver = "2"
members = ["crates/readstat-sys", "crates/readstat", "src-tauri"]

[workspace.package]
edition = "2021"
license = "MIT"
repository = "https://github.com/caovc/stat-data-viewer"

[workspace.dependencies]
arrow = "58"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
